"""Export helpers for professional validation workflows.

The FDS exporter intentionally creates only a skeleton/template file. It is not a
complete certified Fire Dynamics Simulator input and must be completed by a fire
engineer before use.
"""
from __future__ import annotations

from typing import Any, Dict, List


def export_fire_scenario_json(result: Dict[str, Any]) -> Dict[str, Any]:
    """Return a JSON-serialisable fire scenario payload."""
    return result


def export_aset_rset_csv_rows(result: Dict[str, Any]) -> List[Dict[str, Any]]:
    return list(result.get("aset_rset_results", []))


def export_hazard_timeline_csv_rows(result: Dict[str, Any]) -> List[Dict[str, Any]]:
    return list(result.get("smoke_spread", {}).get("hazard_timeline", []))


def create_fds_skeleton(result: Dict[str, Any]) -> str:
    """Create a clearly labelled FDS skeleton for expert completion."""
    scenario = result.get("scenario", {})
    fire_growth = result.get("fire_growth", {})
    fire_origin = scenario.get("fire_origin", result.get("fire_origin", "UNKNOWN"))
    growth_class = scenario.get("growth_class", fire_growth.get("growth_class", "medium"))
    hrr_lines = []
    for row in fire_growth.get("time_series", [])[:20]:
        hrr_lines.append(f"! t={row.get('time_s')}s, HRR={row.get('hrr_kw')} kW, intensity={row.get('intensity')}")
    hrr_comment = "\n".join(hrr_lines) if hrr_lines else "! HRR curve not available"

    return f"""&HEAD CHID='bim_evac_fire_scenario', TITLE='FDS skeleton for expert completion - not certified simulation input' /

! -----------------------------------------------------------------------------
! WARNING
! This file is an FDS skeleton generated by an academic decision-support prototype.
! It is NOT a complete, validated, or certified FDS model.
! Geometry, vents, materials, fire source, mesh, devices and outputs must be
! completed and validated by a qualified fire engineer before simulation.
! -----------------------------------------------------------------------------

! Scenario summary
! Fire origin: {fire_origin}
! Growth class: {growth_class}
! Scenario name: {scenario.get('scenario_name', 'Unnamed scenario')}

! Suggested HRR curve preview from simplified t-squared screening model:
{hrr_comment}

! TODO: Define computational domain / mesh.
! &MESH IJK=..., XB=... /

! TODO: Define materials/surfaces.
! &SURF ID='FUEL_SURFACE', HRRPUA=... /

! TODO: Define fire source at/near BIM space: {fire_origin}
! &OBST XB=..., SURF_ID='FUEL_SURFACE' /

! TODO: Define doors/openings/vents from BIM connections.
! &VENT XB=..., SURF_ID='OPEN' /

! TODO: Define devices and outputs for ASET indicators.
! &DEVC ID='Visibility_Device', QUANTITY='VISIBILITY', XYZ=... /
! &DEVC ID='Temperature_Device', QUANTITY='TEMPERATURE', XYZ=... /

&TAIL /
"""
